modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "fossils_delight"
version = "${version}"
displayName = "Fossils Delight"
authors = "Aethalis and legoaggelos"
description = '''
A Farmer's Delight and Fossils and Archaeology Revival addon
'''
#logoFile = ""

[[dependencies.fossils_delight]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fossils_delight]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fossils_delight]]
modId = "architectury"
mandatory = true
versionRange = "[4.12.94,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.fossils_delight]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.0.55,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.fossils_delight]]
modId = "terrablender"
mandatory = true
versionRange = "[1.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fossils_delight]]
modId = "morehitboxes"
mandatory = true
versionRange = "[1.7.3,)"
ordering = "AFTER"
side = "BOTH"


[[dependencies.fossils_delight]]
modId = "fossil"
mandatory = true
versionRange = "[9.1.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fossils_delight]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1.2.0,)"
ordering = "NONE"
side = "BOTH"